import time
import os
import re
import requests
import logging
from PyQt6.QtCore import QObject, pyqtSignal
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

class SlicerOutputHandler(FileSystemEventHandler):
    def __init__(self, thread):
        super().__init__()
        self.thread = thread
        self.processed_signatures = {}

    def process(self, filepath):
        if os.path.isdir(filepath):
            return
            
        filepath_lower = filepath.lower()
        filename = os.path.basename(filepath)
        
        # Ignore hidden/temporary gcode files generated by Bambu Studio (e.g. .42932.1.gcode)
        # But allow `.3mf` files because Bambu Studio outputs the actual slice as exactly `.3mf`
        if filename.startswith('.') and filename.lower() != '.3mf':
            return

        if not (filepath_lower.endswith('.gcode') or filepath_lower.endswith('.3mf')):
            return

        # Wait a bit to ensure the file is completely written by the slicer
        time.sleep(2)
        
        try:
            stat = os.stat(filepath)
            file_sig = f"{stat.st_size}_{stat.st_mtime}"
        except OSError:
            return
            
        if self.processed_signatures.get(filepath) == file_sig:
            return
            
        self.processed_signatures[filepath] = file_sig
        
        if filepath_lower.endswith('.gcode'):
            data = self.thread.parse_gcode(filepath)
        elif filepath_lower.endswith('.3mf'):
            data = self.thread.parse_3mf(filepath)
            
        logging.info(f"Detected valid slicer output file: {filepath} (Signature: {file_sig})")
        self.thread.file_detected.emit(f"Found new file: {data['filename']}")
        
        self.thread.send_to_api(data)

    def on_created(self, event):
        self.process(event.src_path)

    def on_moved(self, event):
        self.process(event.dest_path)

class SnifferThread(QObject):
    file_detected = pyqtSignal(str)
    file_processed = pyqtSignal(str)
    error_occurred = pyqtSignal(str)

    def __init__(self, config):
        super().__init__()
        self.config = config
        self.observer = None

    def parse_3mf(self, filepath):
        metadata = {
            'filename': os.path.basename(filepath),
            'print_time_seconds': None,
            'filament_weight_g': None,
            'filament_type': None
        }
        try:
            import zipfile
            import xml.etree.ElementTree as ET
            
            with zipfile.ZipFile(filepath, 'r') as z:
                if 'Metadata/slice_info.config' in z.namelist():
                    xml_data = z.read('Metadata/slice_info.config')
                    root = ET.fromstring(xml_data)
                    
                    pred = root.find(".//metadata[@key='prediction']")
                    if pred is not None:
                        metadata['print_time_seconds'] = int(pred.attrib['value'])
                        
                    weight = root.find(".//metadata[@key='weight']")
                    if weight is not None:
                        metadata['filament_weight_g'] = float(weight.attrib['value'])
                        
                    fil = root.find(".//filament")
                    if fil is not None:
                        metadata['filament_type'] = fil.attrib.get('type')
                        
                    obj = root.find(".//object")
                    if obj is not None:
                        name = obj.attrib.get('name', '')
                        if name:
                            # Extract a nice name instead of '.3mf'
                            clean_name = name.split('.stl')[0]
                            metadata['filename'] = f"{clean_name}.3mf"
        except Exception as e:
            logging.error(f"Error parsing 3MF: {e}")
            
        return metadata

    def parse_gcode(self, filepath):
        metadata = {
            'filename': os.path.basename(filepath),
            'print_time_seconds': None,
            'filament_weight_g': None,
            'filament_type': None
        }
        
        try:
            with open(filepath, 'rb') as f:
                head = f.read(8192).decode('utf-8', errors='ignore')
                f.seek(0, os.SEEK_END)
                size = f.tell()
                f.seek(max(size - 8192, 0))
                tail = f.read().decode('utf-8', errors='ignore')
                
                content = head + "\n" + tail
                
                weight_match = re.search(r'; filament (?:used|weight) \[g\] [:=] ([\d.]+)', content)
                if weight_match:
                    metadata['filament_weight_g'] = float(weight_match.group(1))
                
                time_match = re.search(r'; (?:estimated printing time|model print time|model printing time).*?[:=] (.*)', content)
                if time_match:
                    time_str = time_match.group(1).strip()
                    seconds = 0
                    h_match = re.search(r'(\d+)h', time_str)
                    m_match = re.search(r'(\d+)m', time_str)
                    s_match = re.search(r'(\d+)s', time_str)
                    if h_match: seconds += int(h_match.group(1)) * 3600
                    if m_match: seconds += int(m_match.group(1)) * 60
                    if s_match: seconds += int(s_match.group(1))
                    metadata['print_time_seconds'] = seconds
                    
                type_match = re.search(r'; filament_type [:=] (.*)', content)
                if type_match:
                    metadata['filament_type'] = type_match.group(1).strip()
        except Exception as e:
            logging.error(f"Error parsing GCODE: {e}")
            
        return metadata

    def send_to_api(self, data):
        if not data['filename']:
            return
            
        url = self.config.server_url.rstrip('/') + '/api/slicer/sync/'
        headers = {}
        if self.config.api_key:
            headers['X-API-Key'] = self.config.api_key
            
        try:
            response = requests.post(url, json=data, headers=headers, timeout=5)
            if response.status_code == 200:
                logging.info(f"Successfully uploaded metadata for {data['filename']} to Model Foundry.")
                self.file_processed.emit(f"Successfully uploaded {data['filename']}")
            else:
                try:
                    err_msg = response.json().get('message', 'Unknown error')
                except:
                    err_msg = response.text
                logging.error(f"Server rejected {data['filename']}: {err_msg}")
                self.error_occurred.emit(f"Server error: {err_msg}")
        except Exception as e:
            logging.error(f"Network error syncing {data['filename']}: {e}")
            self.error_occurred.emit(f"Failed to connect to server: {e}")

    def start(self):
        if self.observer:
            self.stop()
            
        self.observer = Observer()
        handler = SlicerOutputHandler(self)
        
        has_paths = False
        for path in self.config.watch_directories:
            if os.path.exists(path):
                self.observer.schedule(handler, path, recursive=True)
                has_paths = True
                
        if has_paths:
            self.observer.start()
        else:
            self.error_occurred.emit("No valid watch directories found.")

    def stop(self):
        if self.observer:
            self.observer.stop()
            self.observer.join()
            self.observer = None
